from pydantic import BaseModel, Field


class ScenarioRequest(BaseModel):
    """The HTTP request details defining a specific step execution."""

    method: str
    path: str
    headers: dict[str, str] = Field(default_factory=dict)
    body: str | None = None


class ScenarioStep(BaseModel):
    """An individual operation in an attack scenario sequence."""

    id: str
    description: str
    request: ScenarioRequest
    is_destructive: bool = False


class ScenarioPlan(BaseModel):
    """A multi-step scenario sequence generated by the AI module."""

    name: str
    description: str
    steps: list[ScenarioStep]
    expected_signals: list[str] = Field(default_factory=list)
    stop_conditions: list[str] = Field(default_factory=list)
